import { useState } from 'react';
import { Bar, BarChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { ChartNoAxesColumn, Headset, Utensils, type LucideIcon } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { useSalesFilters } from '../../contexts/sales-filters-context';
import { api } from '../../services/api-client';
import { LoadingSkeleton } from '../ui/states';

type Dimension = 'overall' | 'food' | 'service';
type Segment = { count: number; percent: number };
type TrendGranularity = 'daily' | 'weekly' | 'monthly';
type Trend = { date: string; overall: number; food: number; service: number; responses: number };
type Satisfaction = { summary: { totalResponses: number; averageOverallSatisfaction: number; averageFoodSatisfaction: number; averageServiceSatisfaction: number; satisfied: Segment; neutral: Segment; dissatisfied: Segment; dateRange: { start: string; end: string } }; distribution: Array<{ rating: number; responses: number; percent: number }>; trendGranularity: TrendGranularity; trend: Trend[] };

const labels: Record<Dimension, string> = { overall: 'Overall Satisfaction', food: 'Food Satisfaction', service: 'Service Satisfaction' };
const date = (value: string) => new Intl.DateTimeFormat('en-PH', { dateStyle: 'medium' }).format(new Date(value));
const periodLabel = (value: string, granularity: TrendGranularity) => granularity === 'weekly' ? `Week of ${date(value)}` : granularity === 'monthly' ? new Intl.DateTimeFormat('en-PH', { month: 'short', year: 'numeric' }).format(new Date(`${value}-01T00:00:00`)) : date(value);

function Kpi({ title, value, detail, primary = false }: { title: string; value: string; detail?: string; primary?: boolean }) {
  return <article className={`rounded-xl border p-3.5 ${primary ? 'border-emerald-200 bg-emerald-50/60 dark:border-emerald-800/60 dark:bg-emerald-950/25' : 'border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-900'}`}><p className="text-[11px] font-semibold uppercase tracking-wide text-slate-500">{title}</p><p className={`mt-1.5 font-bold tabular-nums ${primary ? 'text-2xl text-emerald-900 dark:text-emerald-200' : 'text-xl'}`}>{value}</p>{detail ? <p className="mt-0.5 text-xs text-slate-500">{detail}</p> : null}</article>;
}

function ClassificationRow({ label, definition, segment, tone }: { label: string; definition: string; segment: Segment; tone: string }) {
  return <div className="flex gap-2.5"><span aria-hidden="true" className={`mt-0.5 h-14 w-[3px] shrink-0 rounded-full ${tone}`} /><div className="min-w-0 flex-1"><div className="flex items-baseline justify-between gap-3 text-sm"><div><span className="font-medium">{label}</span><p className="mt-0.5 text-xs text-slate-500">{definition}</p></div><span className="whitespace-nowrap tabular-nums"><span className="font-semibold">{segment.percent.toFixed(1)}%</span> <span className="font-normal text-slate-500">· {segment.count.toLocaleString()}</span></span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-200 dark:bg-slate-800"><div aria-label={`${label}: ${segment.percent.toFixed(1)} percent`} className={`h-full rounded-full ${tone}`} style={{ width: `${segment.percent}%` }} /></div></div></div>;
}

function DimensionRow({ label, value, tone, icon: Icon, iconSurface, iconTone }: { label: string; value: number; tone: string; icon: LucideIcon; iconSurface: string; iconTone: string }) {
  const width = Math.min(Math.max((value / 5) * 100, 0), 100);
  return <div className="flex gap-3 rounded-xl border border-slate-200/80 bg-slate-50/50 p-3 transition-colors hover:border-slate-300 hover:bg-slate-50 dark:border-slate-800 dark:bg-slate-950/25 dark:hover:border-slate-700 dark:hover:bg-slate-950/45"><span aria-hidden="true" className={`grid size-10 shrink-0 place-items-center rounded-lg ${iconSurface}`}><Icon className={`size-4 ${iconTone}`} /></span><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-3 text-sm"><span className="font-medium">{label}</span><span className="whitespace-nowrap font-semibold tabular-nums">{value.toFixed(2)} <span className="font-normal text-slate-500">/ 5</span></span></div><div className="mt-2 h-2.5 w-full overflow-hidden rounded-full border border-slate-300/70 bg-slate-200 dark:border-slate-700 dark:bg-slate-950"><div title={`${label}: ${value.toFixed(2)} / 5`} aria-label={`${label}: ${value.toFixed(2)} out of 5`} className={`h-full rounded-full ${tone} transition-[width] duration-300 motion-reduce:transition-none`} style={{ width: `${width}%` }} /></div></div></div>;
}

function TrendTooltip({ active, payload, granularity }: { active?: boolean; payload?: Array<{ payload: Trend; value?: number }>; granularity: TrendGranularity }) {
  const point = payload?.[0]?.payload;
  if (!active || !point) return null;
  return <div className="rounded-lg border border-slate-200 bg-white px-3 py-2 text-xs shadow-md dark:border-slate-700 dark:bg-slate-950"><p className="font-semibold">{periodLabel(point.date, granularity)}</p><p className="mt-1">Average rating: <span className="font-semibold">{Number(payload?.[0]?.value ?? 0).toFixed(2)} / 5</span></p><p className="text-slate-500">Responses: {point.responses.toLocaleString()}</p></div>;
}

export function CustomerSatisfactionPanel() {
  const { filters } = useSalesFilters();
  const [dimension, setDimension] = useState<Dimension>('overall');
  const query = useQuery({ queryKey: ['customer-satisfaction', filters.startDate, filters.endDate], queryFn: async () => (await api.get<{ data: Satisfaction | null }>('/analytics/satisfaction', { params: { startDate: filters.startDate, endDate: filters.endDate } })).data.data });
  if (query.isLoading) return <LoadingSkeleton className="mt-6 h-[38rem] rounded-2xl" />;
  if (query.isError) return <section className="mt-6 rounded-2xl border border-rose-200 bg-rose-50 p-5 text-sm text-rose-700 dark:border-rose-900 dark:bg-rose-950/30 dark:text-rose-200">Customer Satisfaction data could not be loaded. Existing POS-based Customer Analytics remain available.</section>;
  if (!query.data) return <section className="mt-6 rounded-2xl border bg-white p-6 text-center dark:border-slate-800 dark:bg-slate-900"><h2 className="font-semibold">No Customer Feedback Responses</h2><p className="mx-auto mt-2 max-w-xl text-sm text-slate-500">No valid customer feedback responses are available for the selected period.</p><Link to="/data" className="mt-4 inline-flex rounded-lg bg-emerald-800 px-4 py-2 text-sm font-semibold text-white">Go to Data Management</Link></section>;

  const data = query.data;
  const average = data.summary.averageOverallSatisfaction;
  const topRating = data.distribution.reduce((best, item) => item.responses > best.responses ? item : best, data.distribution[0]);
  const distributionDomain = Math.ceil((Math.max(...data.distribution.map((item) => item.responses)) * 1.12) / 25) * 25;
  const trendAboveFour = data.trend.length > 0 && data.trend.every((point) => point[dimension] >= 4);
  const insight = `Overall satisfaction is ${average.toFixed(2)}/5, with ${data.summary.satisfied.percent.toFixed(1)}% of responses rated satisfied. Rating ${topRating.rating} is the most common response; food and service average ${data.summary.averageFoodSatisfaction.toFixed(2)}/5 and ${data.summary.averageServiceSatisfaction.toFixed(2)}/5.${trendAboveFour ? ` ${labels[dimension]} remained at or above 4.0/5 across the selected period.` : ''}`;
  const granularityLabel = data.trendGranularity[0].toUpperCase() + data.trendGranularity.slice(1);

  return <section className="mt-6 rounded-2xl border bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><header><h2 className="font-semibold">Customer Satisfaction</h2><p className="mt-1 text-sm text-slate-500">Customer satisfaction ratings based on optional customer feedback.</p><p className="mt-2 text-xs text-slate-500">Feedback coverage: {date(data.summary.dateRange.start)} – {date(data.summary.dateRange.end)} · Responses: {data.summary.totalResponses.toLocaleString()}</p></header>
    <div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Kpi primary title="Average Satisfaction" value={`${average.toFixed(2)} / 5`} detail="Overall Satisfaction" /><Kpi title="Total Responses" value={data.summary.totalResponses.toLocaleString()} /><Kpi title="Satisfied" value={`${data.summary.satisfied.percent.toFixed(1)}%`} detail={`${data.summary.satisfied.count.toLocaleString()} responses · ratings 4–5`} /><Kpi title="Neutral" value={`${data.summary.neutral.percent.toFixed(1)}%`} detail={`${data.summary.neutral.count.toLocaleString()} responses · rating 3`} /><Kpi title="Dissatisfied" value={`${data.summary.dissatisfied.percent.toFixed(1)}%`} detail={`${data.summary.dissatisfied.count.toLocaleString()} responses · ratings 1–2`} /></div>
    <p className="mt-2.5 text-xs text-slate-500">Satisfaction groups: satisfied (ratings 4–5), neutral (rating 3), dissatisfied (ratings 1–2).</p>
    <div className="mt-5 grid items-stretch gap-5 xl:grid-cols-2"><article className="rounded-xl border border-slate-200 p-4 dark:border-slate-800"><h3 className="font-semibold">Satisfaction by Dimension</h3><p className="mt-1 text-sm text-slate-500">Average ratings on a fixed 0–5 scale.</p><div className="mt-5 space-y-4"><DimensionRow label="Overall Satisfaction" value={average} tone="bg-emerald-700 dark:bg-emerald-500" icon={ChartNoAxesColumn} iconSurface="bg-emerald-100 dark:bg-emerald-500/15" iconTone="text-emerald-700 dark:text-emerald-400" /><DimensionRow label="Food Satisfaction" value={data.summary.averageFoodSatisfaction} tone="bg-amber-500" icon={Utensils} iconSurface="bg-amber-100 dark:bg-amber-400/15" iconTone="text-amber-700 dark:text-amber-300" /><DimensionRow label="Service Satisfaction" value={data.summary.averageServiceSatisfaction} tone="bg-violet-600 dark:bg-violet-500" icon={Headset} iconSurface="bg-violet-100 dark:bg-violet-400/15" iconTone="text-violet-700 dark:text-violet-300" /></div></article><article className="rounded-xl border border-slate-200 p-4 dark:border-slate-800"><h3 className="font-semibold">Satisfaction Overview</h3><p className="mt-1 text-sm text-slate-500">Overall satisfaction classification.</p><p className="mt-1 text-xs text-slate-500">Based on Overall Satisfaction ratings.</p><div className="mt-4 space-y-3"><ClassificationRow label="Satisfied" definition="Ratings 4–5" segment={data.summary.satisfied} tone="bg-emerald-700 dark:bg-emerald-500" /><ClassificationRow label="Neutral" definition="Rating 3" segment={data.summary.neutral} tone="bg-amber-500" /><ClassificationRow label="Dissatisfied" definition="Ratings 1–2" segment={data.summary.dissatisfied} tone="bg-rose-700 dark:bg-rose-500" /></div></article></div>
    <div className="mt-5 grid gap-5 xl:grid-cols-2"><article className="rounded-xl border border-slate-200 p-4 dark:border-slate-800"><h3 className="font-semibold">Rating Distribution (1–5)</h3><p className="mt-1 text-sm text-slate-500">Number of customer feedback responses for each overall satisfaction rating.</p><div className="mt-4 h-72"><ResponsiveContainer><BarChart data={data.distribution} margin={{ top: 8, right: 8, left: -16, bottom: 0 }}><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey="rating" tickLine={false} axisLine={false} /><YAxis allowDecimals={false} domain={[0, distributionDomain]} tickLine={false} axisLine={false} /><Tooltip formatter={(value, _name, item) => [`${Number(value).toLocaleString()} responses · ${Number(item.payload.percent).toFixed(1)}%`, 'Responses']} labelFormatter={(value) => `Rating: ${value}`} /><Bar dataKey="responses" name="Responses" fill="#047857" radius={[6, 6, 0, 0]} barSize={34} /></BarChart></ResponsiveContainer></div></article><article className="rounded-xl border border-slate-200 p-4 dark:border-slate-800"><div className="flex flex-wrap items-start justify-between gap-2"><div><h3 className="font-semibold">Average Satisfaction Trend</h3><p className="mt-1 text-sm text-slate-500">{granularityLabel} average customer rating over the selected period.</p></div><select aria-label="Satisfaction trend dimension" value={dimension} onChange={(event) => setDimension(event.target.value as Dimension)} className="rounded-lg border border-slate-200 bg-white px-2 py-1 text-sm focus:outline-none focus:ring-2 focus:ring-emerald-600 dark:border-slate-700 dark:bg-slate-950"><option value="overall">Overall</option><option value="food">Food</option><option value="service">Service</option></select></div><div className="mt-4 h-72"><ResponsiveContainer><LineChart data={data.trend} margin={{ top: 8, right: 12, left: -16, bottom: 0 }}><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey="date" minTickGap={26} tickFormatter={(value) => data.trendGranularity === 'monthly' ? value : new Intl.DateTimeFormat('en-PH', { month: 'short', day: 'numeric' }).format(new Date(`${value}T00:00:00`))} tickLine={false} axisLine={false} /><YAxis domain={[1, 5]} ticks={[1, 2, 3, 4, 5]} allowDecimals={false} tickLine={false} axisLine={false} /><Tooltip content={<TrendTooltip granularity={data.trendGranularity} />} /><Line type="monotone" dataKey={dimension} name={labels[dimension]} stroke="#047857" strokeWidth={3} dot={{ r: 3, fill: '#047857' }} activeDot={{ r: 5 }} /></LineChart></ResponsiveContainer></div></article></div>
    <article className="mt-5 rounded-xl border border-emerald-900/10 bg-emerald-50/50 p-4 dark:border-emerald-800/40 dark:bg-emerald-950/20"><h3 className="font-semibold">Customer Satisfaction Insight</h3><p className="mt-1.5 text-sm text-slate-600 dark:text-slate-300">{insight}</p></article>
  </section>;
}
