import { DashboardRepository } from "../repositories/dashboard.repository.js";

export type DashboardQuery = { startDate?: string; endDate?: string; salesChannel?: string; salesChannels?: string[]; groupBy?: string; limit?: number };
const amount = (value: unknown) => Number(value ?? 0);
const range = (startDate?: string, endDate?: string) => ({ start: startDate ? new Date(`${startDate}T00:00:00+08:00`) : undefined, end: endDate ? new Date(`${endDate}T23:59:59.999+08:00`) : undefined });
const selectedChannels = (query: DashboardQuery) => query.salesChannels?.length ? query.salesChannels : query.salesChannel ? [query.salesChannel] : undefined;

export class DashboardService {
  constructor(private readonly repo = new DashboardRepository()) {}
  async summary(query: DashboardQuery) { const dates = range(query.startDate, query.endDate); const channels = selectedChannels(query); const [summary, customers, totalProducts] = await Promise.all([this.repo.summary(dates.start, dates.end, channels), this.repo.customers(dates.start, dates.end, channels), this.repo.products()]); return { totalSales: amount(summary._sum.netSales), totalTransactions: summary._count.id, averageOrderValue: amount(summary._avg.netSales), totalCustomers: customers.length, totalProducts, averageGuests: amount(summary._avg.guestCount), dateRange: query }; }
  async grouped(query: DashboardQuery) { const dates = range(query.startDate, query.endDate); const rows = await this.repo.transactions(dates.start, dates.end, selectedChannels(query)); const grouped = new Map<string, { sales: number; transactions: number }>(); for (const row of rows) { const date = new Date(row.occurredAt); const key = query.groupBy === "monthly" ? `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}` : query.groupBy === "weekly" ? `${date.getFullYear()}-W${Math.ceil(((date.getTime() - new Date(date.getFullYear(), 0, 1).getTime() + 86_400_000) / 86_400_000) / 7)}` : date.toISOString().slice(0, 10); const value = grouped.get(key) ?? { sales: 0, transactions: 0 }; value.sales += amount(row.netSales); value.transactions += 1; grouped.set(key, value); } return [...grouped].sort(([left], [right]) => left.localeCompare(right)).map(([date, value]) => ({ date, ...value })); }
  async distribution(field: "salesChannel" | "orderType", query: DashboardQuery) { const dates = range(query.startDate, query.endDate); const rows = await this.repo.transactions(dates.start, dates.end, selectedChannels(query)); const grouped = new Map<string, { sales: number; transactions: number }>(); for (const row of rows) { const key = row[field]; const value = grouped.get(key) ?? { sales: 0, transactions: 0 }; value.sales += amount(row.netSales); value.transactions += 1; grouped.set(key, value); } return [...grouped].map(([key, value]) => field === "salesChannel" ? { channel: key, ...value } : { orderType: key, ...value }); }
  async productRank(query: DashboardQuery) { const dates = range(query.startDate, query.endDate); const metrics = await this.repo.productMetrics(dates.start, dates.end, selectedChannels(query)); const details = await this.repo.productDetails(metrics.map((metric) => metric.productId)); const detailById = new Map(details.map((product) => [product.id, product])); return metrics.flatMap((metric) => { const product = detailById.get(metric.productId); return product ? [{ productId: product.id, productName: product.name, category: product.category.name, quantitySold: amount(metric._sum.quantity), revenue: amount(metric._sum.salesAmount) }] : []; }).sort((left, right) => right.revenue - left.revenue).slice(0, query.limit ?? 10); }
  async categories(query: DashboardQuery) { const products = await this.productRank({ ...query, limit: 100_000 }); const grouped = new Map<string, { revenue: number; quantitySold: number }>(); for (const product of products) { const value = grouped.get(product.category) ?? { revenue: 0, quantitySold: 0 }; value.revenue += product.revenue; value.quantitySold += product.quantitySold; grouped.set(product.category, value); } return [...grouped].map(([category, value]) => ({ category, ...value })).sort((left, right) => right.revenue - left.revenue); }
  async hourly(query: DashboardQuery) { const dates = range(query.startDate, query.endDate); const rows = await this.repo.transactions(dates.start, dates.end, selectedChannels(query)); const grouped = new Map<number, { revenue: number; transactions: number }>(); for (const row of rows) { const hour = new Date(row.occurredAt).getHours(); const value = grouped.get(hour) ?? { revenue: 0, transactions: 0 }; value.revenue += amount(row.netSales); value.transactions += 1; grouped.set(hour, value); } return [...grouped].sort(([left], [right]) => left - right).map(([hour, value]) => ({ hour, ...value })); }
  imports() { return this.repo.imports(); }
}
