CREATE EXTENSION IF NOT EXISTS citext;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TYPE "UserRole" AS ENUM ('ADMINISTRATOR', 'MANAGER', 'STAFF');
CREATE TYPE "ImportStatus" AS ENUM ('IN_PROGRESS', 'COMPLETED', 'FAILED');
CREATE TYPE "ForecastGranularity" AS ENUM ('DAILY', 'WEEKLY', 'MONTHLY');

CREATE TABLE "users" ("id" UUID NOT NULL DEFAULT gen_random_uuid(), "email" CITEXT NOT NULL, "passwordHash" TEXT NOT NULL, "firstName" TEXT NOT NULL, "lastName" TEXT NOT NULL, "role" "UserRole" NOT NULL DEFAULT 'STAFF', "isActive" BOOLEAN NOT NULL DEFAULT true, "lastLoginAt" TIMESTAMPTZ(6), "deletedAt" TIMESTAMPTZ(6), "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMPTZ(6) NOT NULL, CONSTRAINT "users_pkey" PRIMARY KEY ("id"));
CREATE TABLE "customers" ("id" UUID NOT NULL DEFAULT gen_random_uuid(), "externalRef" TEXT, "firstName" TEXT, "lastName" TEXT, "email" CITEXT, "phone" TEXT, "dateOfBirth" DATE, "notes" TEXT, "deletedAt" TIMESTAMPTZ(6), "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMPTZ(6) NOT NULL, CONSTRAINT "customers_pkey" PRIMARY KEY ("id"));
CREATE TABLE "categories" ("id" UUID NOT NULL DEFAULT gen_random_uuid(), "name" TEXT NOT NULL, "sourceKey" TEXT NOT NULL, "deletedAt" TIMESTAMPTZ(6), "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMPTZ(6) NOT NULL, CONSTRAINT "categories_pkey" PRIMARY KEY ("id"));
CREATE TABLE "products" ("id" UUID NOT NULL DEFAULT gen_random_uuid(), "categoryId" UUID NOT NULL, "name" TEXT NOT NULL, "sourceKey" TEXT NOT NULL, "sku" TEXT, "currentPrice" DECIMAL(14,2), "isActive" BOOLEAN NOT NULL DEFAULT true, "deletedAt" TIMESTAMPTZ(6), "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMPTZ(6) NOT NULL, CONSTRAINT "products_pkey" PRIMARY KEY ("id"));
CREATE TABLE "import_batches" ("id" UUID NOT NULL DEFAULT gen_random_uuid(), "sourceChecksum" TEXT NOT NULL, "status" "ImportStatus" NOT NULL DEFAULT 'IN_PROGRESS', "transactionFile" TEXT NOT NULL, "productSalesFile" TEXT NOT NULL, "paymentsFile" TEXT NOT NULL, "totalRows" INTEGER NOT NULL DEFAULT 0, "processedRows" INTEGER NOT NULL DEFAULT 0, "importedTransactions" INTEGER NOT NULL DEFAULT 0, "importedItems" INTEGER NOT NULL DEFAULT 0, "importedPayments" INTEGER NOT NULL DEFAULT 0, "skippedTransactions" INTEGER NOT NULL DEFAULT 0, "errorCount" INTEGER NOT NULL DEFAULT 0, "startedAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, "completedAt" TIMESTAMPTZ(6), "createdById" UUID, CONSTRAINT "import_batches_pkey" PRIMARY KEY ("id"));
CREATE TABLE "transactions" ("id" UUID NOT NULL DEFAULT gen_random_uuid(), "sourceTransactionId" TEXT NOT NULL, "invoiceNo" TEXT NOT NULL, "customerId" UUID, "importBatchId" UUID, "occurredAt" TIMESTAMPTZ(6) NOT NULL, "guestCount" INTEGER, "orderType" TEXT NOT NULL, "salesChannel" TEXT NOT NULL, "grossSales" DECIMAL(14,2) NOT NULL, "serviceCharge" DECIMAL(14,2) NOT NULL DEFAULT 0, "discountType" TEXT, "discountAmount" DECIMAL(14,2) NOT NULL DEFAULT 0, "amountDue" DECIMAL(14,2) NOT NULL, "netSales" DECIMAL(14,2) NOT NULL, "deletedAt" TIMESTAMPTZ(6), "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMPTZ(6) NOT NULL, CONSTRAINT "transactions_pkey" PRIMARY KEY ("id"));
CREATE TABLE "transaction_items" ("id" UUID NOT NULL DEFAULT gen_random_uuid(), "transactionId" UUID NOT NULL, "productId" UUID NOT NULL, "sourceRow" INTEGER NOT NULL, "quantity" INTEGER NOT NULL, "unitPrice" DECIMAL(14,2) NOT NULL, "salesAmount" DECIMAL(14,2) NOT NULL, "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMPTZ(6) NOT NULL, CONSTRAINT "transaction_items_pkey" PRIMARY KEY ("id"));
CREATE TABLE "payments" ("id" UUID NOT NULL DEFAULT gen_random_uuid(), "transactionId" UUID NOT NULL, "sourceRow" INTEGER NOT NULL, "paymentMethod" TEXT NOT NULL, "paymentProvider" TEXT, "amount" DECIMAL(14,2) NOT NULL, "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMPTZ(6) NOT NULL, CONSTRAINT "payments_pkey" PRIMARY KEY ("id"));
CREATE TABLE "forecasts" ("id" UUID NOT NULL DEFAULT gen_random_uuid(), "modelName" TEXT NOT NULL, "granularity" "ForecastGranularity" NOT NULL, "targetDate" DATE NOT NULL, "predicted" DECIMAL(14,2) NOT NULL, "lowerBound" DECIMAL(14,2), "upperBound" DECIMAL(14,2), "actual" DECIMAL(14,2), "mae" DECIMAL(14,4), "mape" DECIMAL(14,4), "metadata" JSONB, "generatedAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMPTZ(6) NOT NULL, CONSTRAINT "forecasts_pkey" PRIMARY KEY ("id"));
CREATE TABLE "import_errors" ("id" UUID NOT NULL DEFAULT gen_random_uuid(), "importBatchId" UUID NOT NULL, "sourceFile" TEXT NOT NULL, "rowNumber" INTEGER, "field" TEXT, "message" TEXT NOT NULL, "rawData" JSONB, "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "import_errors_pkey" PRIMARY KEY ("id"));
CREATE TABLE "audit_logs" ("id" UUID NOT NULL DEFAULT gen_random_uuid(), "actorId" UUID, "action" TEXT NOT NULL, "entityType" TEXT NOT NULL, "entityId" TEXT, "metadata" JSONB, "ipAddress" INET, "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "audit_logs_pkey" PRIMARY KEY ("id"));

CREATE UNIQUE INDEX "users_email_key" ON "users"("email"); CREATE UNIQUE INDEX "customers_externalRef_key" ON "customers"("externalRef"); CREATE UNIQUE INDEX "categories_sourceKey_key" ON "categories"("sourceKey"); CREATE UNIQUE INDEX "categories_name_deletedAt_key" ON "categories"("name", "deletedAt"); CREATE UNIQUE INDEX "products_sourceKey_key" ON "products"("sourceKey"); CREATE UNIQUE INDEX "products_sku_key" ON "products"("sku"); CREATE UNIQUE INDEX "transactions_sourceTransactionId_key" ON "transactions"("sourceTransactionId"); CREATE UNIQUE INDEX "transactions_invoiceNo_key" ON "transactions"("invoiceNo"); CREATE UNIQUE INDEX "transaction_items_transactionId_sourceRow_key" ON "transaction_items"("transactionId", "sourceRow"); CREATE UNIQUE INDEX "payments_transactionId_sourceRow_key" ON "payments"("transactionId", "sourceRow"); CREATE UNIQUE INDEX "forecasts_modelName_granularity_targetDate_generatedAt_key" ON "forecasts"("modelName", "granularity", "targetDate", "generatedAt"); CREATE UNIQUE INDEX "import_batches_sourceChecksum_key" ON "import_batches"("sourceChecksum");
CREATE INDEX "transactions_occurredAt_deletedAt_idx" ON "transactions"("occurredAt", "deletedAt"); CREATE INDEX "transactions_customerId_occurredAt_idx" ON "transactions"("customerId", "occurredAt"); CREATE INDEX "transactions_orderType_occurredAt_idx" ON "transactions"("orderType", "occurredAt"); CREATE INDEX "transactions_salesChannel_occurredAt_idx" ON "transactions"("salesChannel", "occurredAt"); CREATE INDEX "products_categoryId_isActive_idx" ON "products"("categoryId", "isActive"); CREATE INDEX "transaction_items_productId_idx" ON "transaction_items"("productId"); CREATE INDEX "payments_paymentMethod_idx" ON "payments"("paymentMethod"); CREATE INDEX "forecasts_granularity_targetDate_idx" ON "forecasts"("granularity", "targetDate"); CREATE INDEX "import_batches_status_startedAt_idx" ON "import_batches"("status", "startedAt"); CREATE INDEX "import_errors_importBatchId_sourceFile_idx" ON "import_errors"("importBatchId", "sourceFile"); CREATE INDEX "audit_logs_entityType_entityId_idx" ON "audit_logs"("entityType", "entityId"); CREATE INDEX "audit_logs_actorId_createdAt_idx" ON "audit_logs"("actorId", "createdAt");

ALTER TABLE "products" ADD CONSTRAINT "products_categoryId_fkey" FOREIGN KEY ("categoryId") REFERENCES "categories"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "transactions" ADD CONSTRAINT "transactions_customerId_fkey" FOREIGN KEY ("customerId") REFERENCES "customers"("id") ON DELETE SET NULL ON UPDATE CASCADE; ALTER TABLE "transactions" ADD CONSTRAINT "transactions_importBatchId_fkey" FOREIGN KEY ("importBatchId") REFERENCES "import_batches"("id") ON DELETE SET NULL ON UPDATE CASCADE; ALTER TABLE "transaction_items" ADD CONSTRAINT "transaction_items_transactionId_fkey" FOREIGN KEY ("transactionId") REFERENCES "transactions"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "transaction_items" ADD CONSTRAINT "transaction_items_productId_fkey" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "payments" ADD CONSTRAINT "payments_transactionId_fkey" FOREIGN KEY ("transactionId") REFERENCES "transactions"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "import_batches" ADD CONSTRAINT "import_batches_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE; ALTER TABLE "import_errors" ADD CONSTRAINT "import_errors_importBatchId_fkey" FOREIGN KEY ("importBatchId") REFERENCES "import_batches"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "audit_logs" ADD CONSTRAINT "audit_logs_actorId_fkey" FOREIGN KEY ("actorId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;
