import cors from 'cors';
import express from 'express';
import rateLimit from 'express-rate-limit';
import helmet from 'helmet';
import pino from 'pino';
import swaggerUi from 'swagger-ui-express';
import { env } from './config/env.js';
import { openapi } from './docs/openapi.js';
import { errorHandler } from './lib/errors.js';
import { apiRouter } from './routes/api.js';

export const app = express();
const logger = pino({ level: env.NODE_ENV === 'production' ? 'info' : 'debug' });
app.disable('x-powered-by');
app.use((request, response, next) => { response.on('finish', () => logger.info({ method: request.method, path: request.path, statusCode: response.statusCode }, 'request completed')); next(); });
app.use(helmet());
app.use(cors({ origin: env.CORS_ORIGIN.split(',').map((origin) => origin.trim()), credentials: true }));
app.use(express.json({ limit: '1mb' }));
app.use(rateLimit({ windowMs: 15 * 60 * 1000, limit: 300, standardHeaders: 'draft-8', legacyHeaders: false }));
app.get('/health', (_request, response) => response.json({ status: 'ok' }));
app.use('/api/docs', swaggerUi.serve, swaggerUi.setup(openapi, { explorer: true }));
app.get('/api/docs.json', (_request, response) => response.json(openapi));
app.use('/api/v1', apiRouter);
app.use(errorHandler);
