import { useState } from 'react';
import { Area, AreaChart, CartesianGrid, Legend, Line, LineChart, ReferenceLine, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { EmptyState, ErrorState, LoadingSkeleton } from '../components/ui/states';
import { useGenerateNetSalesForecast } from '../hooks/useForecasting';
import type { NetSalesForecast } from '../services/forecasting.api';

const pesos = (value: number) => `${value < 0 ? '-' : ''}₱${Math.round(Math.abs(value)).toLocaleString('en-PH')}`;
const tick = (value: number) => `₱${Math.round(value / 1000)}K`;
const targets = [['net_sales', 'Net Sales', false], ['transactions', 'Transaction Volume', false], ['guests', 'Guest Count', false], ['product_quantity', 'Product Demand', true], ['category_sales', 'Category Sales', true]] as const;
const monthTicks = ['2026-01-01', '2026-02-01', '2026-03-01', '2026-04-01', '2026-05-01', '2026-06-01', '2026-07-01'];
const month = (date: string) => new Intl.DateTimeFormat('en', { month: 'short' }).format(new Date(`${date}T00:00:00Z`));
const Card = ({ title, value }: { title: string; value: string }) => <article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><p className="text-sm text-slate-500">{title}</p><p className="mt-2 text-2xl font-bold">{value}</p></article>;

function CurrencyTooltip({ active, payload, label, currency }: { active?: boolean; payload?: Array<{ name: string; value: number; color: string }>; label?: string; currency: boolean }) {
  if (!active || !payload?.length) return null;
  return <div className="rounded-lg border bg-white p-3 text-sm shadow-lg dark:bg-slate-900"><p className="font-semibold">{new Date(`${label}T00:00:00Z`).toLocaleDateString('en-PH', { month: 'long', day: 'numeric', year: 'numeric' })}</p>{payload.filter((item) => item.value !== undefined && item.value !== null).map((item) => <p key={item.name} style={{ color: item.color }}>{item.name}: {currency ? pesos(item.value) : Math.round(item.value).toLocaleString()}</p>)}</div>;
}

function Results({ data, target }: { data: NetSalesForecast; target: 'net_sales' | 'transactions' | 'guests' }) {
  const historical = data.historical ?? [];
  const validation = data.validation ?? [];
  const forecast = data.forecast ?? [];
  const chart = [...historical.map((row) => ({ date: row.date, 'Training Actual': row.value })), ...validation.map((row) => ({ date: row.date, 'Validation Actual': row.actual, 'Validation Predicted': row.predicted })), ...forecast.map((row) => ({ date: row.date, 'Future Forecast': row.predicted }))];
  const futureChart = forecast.map((row) => ({ date: row.date, Forecast: row.predicted, 'Lower Bound': row.lowerBound, 'Upper Bound': row.upperBound }));
  const allValues = [...historical.map((row) => row.value), ...validation.flatMap((row) => [row.actual, row.predicted]), ...forecast.flatMap((row) => [row.predicted, row.lowerBound, row.upperBound])];
  const padding = (Math.max(...allValues) - Math.min(...allValues)) * 0.1 || 1;
  const domain: [number, number] = [Math.min(...allValues) - padding, Math.max(...allValues) + padding];
  const average = forecast.reduce((sum, row) => sum + row.predicted, 0) / (forecast.length || 1);
  const historicalAverage = historical.reduce((sum, row) => sum + row.value, 0) / (historical.length || 1);
  const currency = target === 'net_sales'; const unit = target === 'transactions' ? 'transactions' : 'guests'; const display = (value: number) => currency ? pesos(value) : Math.round(value).toLocaleString(); const axis = currency ? tick : (value: number) => Math.round(value).toString();
  return <>
    <article className="rounded-2xl border bg-white p-5 dark:bg-slate-900"><h3 className="font-semibold">Model Validation</h3><p className="mt-2 text-sm text-slate-500">Training: Jan 1 – May 31, 2026 · Validation: Jun 1 – Jun 30, 2026 · Forecast: Jul 1 onward</p><p className="mt-2 text-sm">Validation observations: {data.metrics.validationObservations} · Excluded from MAPE (actual = 0): {data.metrics.excludedMapeObservations}</p></article>
    <div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Card title={currency ? 'Forecast Average' : `Forecast Average (${unit}/day)`} value={display(average)} /><Card title={currency ? 'Forecast Total' : `Forecast Total (${unit})`} value={display(forecast.reduce((sum, row) => sum + row.predicted, 0))} /><Card title={currency ? 'Historical Average' : `Historical Average (${unit}/day)`} value={display(historicalAverage)} /><Card title="MAPE" value={data.metrics.mape === null ? '—' : `${data.metrics.mape.toFixed(2)}%`} /><Card title={currency ? 'RMSE' : `RMSE (${unit})`} value={data.metrics.rmse === null ? '—' : display(data.metrics.rmse)} /></div>
    <article className="mt-6 rounded-2xl border bg-white p-5 dark:bg-slate-900"><h3 className="mb-4 font-semibold">Training → Validation → Future Forecast</h3><div className="h-80"><ResponsiveContainer><LineChart data={chart}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="date" ticks={monthTicks} tickFormatter={month} /><YAxis domain={domain} tickFormatter={axis} /><Tooltip content={<CurrencyTooltip currency={currency} />} /><Legend /><ReferenceLine x="2026-06-01" stroke="#64748b" strokeDasharray="4 4" label={{ value: 'VALIDATION', position: 'top', fill: '#64748b' }} /><ReferenceLine x="2026-07-01" stroke="#64748b" strokeDasharray="4 4" label={{ value: 'FORECAST', position: 'top', fill: '#64748b' }} /><Line dataKey="Training Actual" stroke="#047857" strokeWidth={3} dot={false} /><Line dataKey="Validation Actual" stroke="#0f766e" strokeWidth={3} dot={false} /><Line dataKey="Validation Predicted" stroke="#b45309" strokeWidth={3} strokeDasharray="6 4" dot={false} /><Line dataKey="Future Forecast" stroke="#7c3aed" strokeWidth={3} strokeDasharray="6 4" dot={false} /></LineChart></ResponsiveContainer></div></article>
    <article className="mt-6 rounded-2xl border bg-white p-5 dark:bg-slate-900"><h3 className="mb-4 font-semibold">Forecast Confidence Interval</h3><div className="h-80"><ResponsiveContainer><AreaChart data={futureChart}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="date" /><YAxis tickFormatter={axis} /><Tooltip content={<CurrencyTooltip currency={currency} />} /><Legend /><Area dataKey="Upper Bound" stroke="#d97706" fill="#fef3c7" /><Area dataKey="Lower Bound" stroke="#b45309" fill="#fff" /><Line dataKey="Forecast" stroke="#7c3aed" strokeWidth={3} /></AreaChart></ResponsiveContainer></div></article>
    <article className="mt-6 rounded-2xl border bg-white p-5 dark:bg-slate-900"><h3 className="font-semibold">Validation Results</h3><p className="mt-1 text-sm text-slate-500">SARIMA · Order (1,1,1) · Seasonal order (1,0,1,7)</p><div className="mt-4 max-h-[620px] overflow-auto"><table className="w-full min-w-[34rem] text-sm"><thead className="sticky top-0 bg-white text-left text-slate-500 dark:bg-slate-900"><tr><th>Date</th><th className="text-right">Actual</th><th className="text-right">Predicted</th><th className="text-right">Error</th></tr></thead><tbody>{validation.map((row) => <tr key={row.date} className="border-t"><td className="py-2">{row.date}</td><td className="text-right">{display(row.actual)}</td><td className="text-right">{display(row.predicted)}</td><td className="text-right">{display(row.error)}</td></tr>)}</tbody></table></div></article>
    <article className="mt-6 rounded-2xl border bg-white p-5 dark:bg-slate-900"><h3 className="font-semibold">Future Forecast</h3><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[34rem] text-sm"><thead className="text-left text-slate-500"><tr><th>Date</th><th className="text-right">Forecast</th><th className="text-right">Lower Bound</th><th className="text-right">Upper Bound</th></tr></thead><tbody>{forecast.map((row) => <tr key={row.date} className="border-t"><td className="py-2">{row.date}</td><td className="text-right">{display(row.predicted)}</td><td className="text-right">{display(row.lowerBound)}</td><td className="text-right">{display(row.upperBound)}</td></tr>)}</tbody></table></div></article>
  </>;
}

export function ForecastingPage() {
  const [horizon, setHorizon] = useState(14); const [target, setTarget] = useState<'net_sales' | 'transactions' | 'guests'>('net_sales');
  const [result, setResult] = useState<NetSalesForecast | null>(null);
  const generate = useGenerateNetSalesForecast();
  const errorMessage = generate.error instanceof Error ? generate.error.message : 'Unknown API error.';
  return <section><div className="mb-6"><p className="text-sm font-medium text-amber-700">Under the Balete</p><h2 className="mt-1 text-3xl font-bold">Forecasting Center</h2><p className="mt-2 text-slate-500">Intentional SARIMA forecasting from PostgreSQL history.</p></div><div className="mb-6 flex flex-wrap items-center gap-3">{targets.map(([value, label, disabled]) => <button key={value} disabled={disabled} onClick={() => { if (value === 'net_sales' || value === 'transactions' || value === 'guests') setTarget(value); }} className={`rounded-lg px-3 py-2 text-sm ${disabled ? 'cursor-not-allowed border opacity-50' : target === value ? 'bg-emerald-800 text-white' : 'border bg-white dark:bg-slate-900'}`}>{label}{disabled ? ' (unavailable)' : ''}</button>)}<select value={horizon} onChange={(event) => setHorizon(Number(event.target.value))} className="rounded-lg border bg-white px-3 py-2 dark:bg-slate-900"><option value="7">7 days</option><option value="14">14 days</option><option value="30">30 days</option></select><button disabled={generate.isPending} onClick={() => generate.mutate({ target, horizon }, { onSuccess: setResult })} className="rounded-lg bg-amber-500 px-4 py-2 font-semibold text-emerald-950 disabled:cursor-not-allowed disabled:opacity-60">{generate.isPending ? 'Generating Forecast...' : 'Generate Forecast'}</button></div>{generate.isError && <ErrorState message={`Forecast generation failed: ${errorMessage}`} />}{generate.isPending && !result ? <LoadingSkeleton className="h-96" /> : result?.available ? <Results data={result} target={target} /> : <EmptyState title={result?.reason ?? 'Select a horizon and generate a forecast.'} />}</section>;
}
