import { useState, type ChangeEvent, type FormEvent } from 'react';
import axios from 'axios';
import { Pencil, Plus, Power, RotateCcw } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useCreateUser, useSetUserActive, useUpdateUser, useUsers } from '../hooks/use-users';
import type { ManagedUser } from '../services/users.api';
import type { UserRole } from '../types/auth';
import { LoadingSkeleton } from '../components/ui/states';

const roles: UserRole[] = ['ADMINISTRATOR', 'MANAGER', 'STAFF'];
const roleLabel = (role: UserRole) => role.charAt(0) + role.slice(1).toLowerCase();
const errorMessage = (error: unknown) => axios.isAxiosError(error) ? (error.response?.data?.error?.message ?? error.response?.data?.message ?? 'Unable to complete that action.') : 'Unable to complete that action.';
type Fields = { firstName: string; lastName: string; email: string; role: UserRole; password: string; confirmation: string };
const empty: Fields = { firstName: '', lastName: '', email: '', role: 'STAFF', password: '', confirmation: '' };

function Form({ user, close }: { user?: ManagedUser; close: () => void }) {
  const create = useCreateUser(); const update = useUpdateUser();
  const [value, setValue] = useState<Fields>(user ? { firstName: user.firstName, lastName: user.lastName, email: user.email, role: user.role, password: '', confirmation: '' } : empty); const [error, setError] = useState('');
  const set = (name: keyof Fields) => (event: ChangeEvent<HTMLInputElement | HTMLSelectElement>) => setValue((old) => ({ ...old, [name]: event.target.value }));
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(''); if (!user && value.password.length < 12) return setError('Temporary password must be at least 12 characters.'); if ((value.password || value.confirmation) && value.password !== value.confirmation) return setError('Passwords do not match.'); try { if (user) await update.mutateAsync({ id: user.id, firstName: value.firstName, lastName: value.lastName, email: value.email, role: value.role, ...(value.password ? { password: value.password } : {}) }); else await create.mutateAsync({ firstName: value.firstName, lastName: value.lastName, email: value.email, role: value.role, password: value.password }); close(); } catch (reason) { setError(errorMessage(reason)); } };
  const pending = create.isPending || update.isPending;
  return <form onSubmit={submit} className="mt-5 grid gap-3 rounded-xl border border-slate-200 bg-slate-50 p-4 dark:border-slate-700 dark:bg-slate-950/40 sm:grid-cols-2"><label>First name<input required value={value.firstName} onChange={set('firstName')} className="mt-1 w-full rounded-lg border p-2 dark:border-slate-700 dark:bg-slate-900" /></label><label>Last name<input required value={value.lastName} onChange={set('lastName')} className="mt-1 w-full rounded-lg border p-2 dark:border-slate-700 dark:bg-slate-900" /></label><label className="sm:col-span-2">Email<input required type="email" value={value.email} onChange={set('email')} className="mt-1 w-full rounded-lg border p-2 dark:border-slate-700 dark:bg-slate-900" /></label><label>Role<select value={value.role} onChange={set('role')} className="mt-1 w-full rounded-lg border p-2 dark:border-slate-700 dark:bg-slate-900">{roles.map((role) => <option key={role}>{role}</option>)}</select></label><label>{user ? 'New password (optional)' : 'Temporary password'}<input required={!user} type="password" autoComplete="new-password" value={value.password} onChange={set('password')} className="mt-1 w-full rounded-lg border p-2 dark:border-slate-700 dark:bg-slate-900" /></label><label className="sm:col-span-2">Confirm password<input required={!user || Boolean(value.password)} type="password" autoComplete="new-password" value={value.confirmation} onChange={set('confirmation')} className="mt-1 w-full rounded-lg border p-2 dark:border-slate-700 dark:bg-slate-900" /></label>{error ? <p className="sm:col-span-2 text-sm text-red-600 dark:text-red-400">{error}</p> : null}<div className="flex gap-2 sm:col-span-2"><button disabled={pending} className="rounded-lg bg-amber-400 px-4 py-2 font-medium text-slate-950 disabled:opacity-60">{pending ? 'Saving…' : user ? 'Save user' : 'Create user'}</button><button type="button" onClick={close} className="rounded-lg border px-4 py-2 dark:border-slate-700">Cancel</button></div></form>;
}

export function UserManagementPage() {
  const list = useUsers(); const active = useSetUserActive(); const [form, setForm] = useState<'create' | ManagedUser | null>(null); const [error, setError] = useState('');
  const toggle = async (user: ManagedUser) => { if (!window.confirm(`${user.isActive ? 'Deactivate' : 'Reactivate'} ${user.email}?`)) return; setError(''); try { await active.mutateAsync({ id: user.id, active: !user.isActive }); } catch (reason) { setError(errorMessage(reason)); } };
  if (list.isLoading) return <div className="space-y-4"><LoadingSkeleton className="h-16" /><LoadingSkeleton className="h-72" /></div>;
  if (list.isError) return <section className="rounded-xl border border-red-200 bg-red-50 p-5 text-red-800 dark:border-red-900 dark:bg-red-950/30 dark:text-red-200">{errorMessage(list.error)}</section>;
  return <section><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-wider text-emerald-600">Settings</p><h2 className="mt-1 text-3xl font-bold">User Management</h2><p className="mt-2 text-slate-500 dark:text-slate-400">Manage internal access without exposing credentials.</p></div><div className="flex gap-2"><Link to="/settings" className="rounded-lg border px-4 py-2 dark:border-slate-700">Back to Settings</Link><button onClick={() => setForm('create')} className="inline-flex items-center gap-2 rounded-lg bg-amber-400 px-4 py-2 font-medium text-slate-950"><Plus size={18} /> Add User</button></div></div>{form ? <Form user={form === 'create' ? undefined : form} close={() => setForm(null)} /> : null}{error ? <p className="mt-4 text-sm text-red-600 dark:text-red-400">{error}</p> : null}<div className="mt-6 overflow-x-auto rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900"><table className="min-w-full text-left text-sm"><thead className="border-b border-slate-200 text-xs uppercase tracking-wide text-slate-500 dark:border-slate-800"><tr><th className="p-4">Name</th><th className="p-4">Email</th><th className="p-4">Role</th><th className="p-4">Status</th><th className="p-4">Last login</th><th className="p-4 text-right">Actions</th></tr></thead><tbody>{list.data?.length ? list.data.map((user) => <tr key={user.id} className="border-b border-slate-100 last:border-0 dark:border-slate-800"><td className="p-4 font-medium">{user.firstName} {user.lastName}</td><td className="p-4 text-slate-500 dark:text-slate-400">{user.email}</td><td className="p-4"><span className="rounded-full bg-slate-100 px-2 py-1 text-xs dark:bg-slate-800">{roleLabel(user.role)}</span></td><td className="p-4"><span className={user.isActive ? 'text-emerald-600' : 'text-slate-500'}>{user.isActive ? 'Active' : 'Inactive'}</span></td><td className="p-4 text-slate-500 dark:text-slate-400">{user.lastLoginAt ? new Date(user.lastLoginAt).toLocaleString() : 'Never'}</td><td className="p-4"><div className="flex justify-end gap-2"><button aria-label={`Edit ${user.email}`} onClick={() => setForm(user)} className="rounded-lg border p-2 dark:border-slate-700"><Pencil size={16} /></button><button aria-label={`${user.isActive ? 'Deactivate' : 'Reactivate'} ${user.email}`} disabled={active.isPending} onClick={() => void toggle(user)} className="rounded-lg border p-2 dark:border-slate-700">{user.isActive ? <Power size={16} /> : <RotateCcw size={16} />}</button></div></td></tr>) : <tr><td colSpan={6} className="p-10 text-center text-slate-500">No user accounts found.</td></tr>}</tbody></table></div></section>;
}
