import swaggerJSDoc from 'swagger-jsdoc';

export const openapi = swaggerJSDoc({
  definition: {
    openapi: '3.0.3',
    info: { title: 'METRICAST API', version: '1.0.0', description: 'Under the Balete Restaurant business intelligence API.' },
    servers: [{ url: '/api/v1', description: 'Current API' }],
    components: {
      securitySchemes: { bearerAuth: { type: 'http', scheme: 'bearer', bearerFormat: 'JWT' } },
      schemas: {
        Error: { type: 'object', properties: { error: { type: 'object', properties: { code: { type: 'string' }, message: { type: 'string' } } } } },
        User: { type: 'object', required: ['id', 'email', 'role'], properties: { id: { type: 'string', format: 'uuid' }, email: { type: 'string', format: 'email' }, firstName: { type: 'string' }, lastName: { type: 'string' }, role: { type: 'string', enum: ['ADMINISTRATOR', 'MANAGER', 'STAFF'] }, isActive: { type: 'boolean' } } },
        Category: { type: 'object', properties: { id: { type: 'string', format: 'uuid' }, name: { type: 'string' }, sourceKey: { type: 'string' } } },
        Product: { type: 'object', properties: { id: { type: 'string', format: 'uuid' }, categoryId: { type: 'string', format: 'uuid' }, name: { type: 'string' }, sourceKey: { type: 'string' }, currentPrice: { type: 'number' } } },
        Customer: { type: 'object', properties: { id: { type: 'string', format: 'uuid' }, email: { type: 'string' }, phone: { type: 'string' } } },
        Transaction: { type: 'object', properties: { id: { type: 'string', format: 'uuid' }, sourceTransactionId: { type: 'string' }, invoiceNo: { type: 'string' }, occurredAt: { type: 'string', format: 'date-time' }, netSales: { type: 'number' } } },
        Payment: { type: 'object', properties: { id: { type: 'string', format: 'uuid' }, transactionId: { type: 'string', format: 'uuid' }, paymentMethod: { type: 'string' }, amount: { type: 'number' } } }
      }
    },
    paths: {
      '/auth/login': { post: { tags: ['Authentication'], summary: 'Login', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['email', 'password'], properties: { email: { type: 'string', format: 'email' }, password: { type: 'string', format: 'password' } } } } } }, responses: { '200': { description: 'Authenticated.' }, '401': { description: 'Invalid credentials.' } } } },
      '/auth/refresh': { post: { tags: ['Authentication'], summary: 'Rotate the secure refresh token', responses: { '200': { description: 'New access token and refresh cookie.' }, '401': { description: 'Invalid or expired refresh token.' } } } },
      '/auth/logout': { post: { tags: ['Authentication'], security: [{ bearerAuth: [] }], summary: 'Revoke the current refresh token and clear its cookie', responses: { '204': { description: 'Logged out.' } } } },
      '/auth/me': { get: { tags: ['Authentication'], security: [{ bearerAuth: [] }], summary: 'Get the authenticated user', responses: { '200': { description: 'Current user.', content: { 'application/json': { schema: { $ref: '#/components/schemas/User' } } } }, '401': { description: 'Unauthenticated.' } } } },
      '/auth/change-password': { post: { tags: ['Authentication'], security: [{ bearerAuth: [] }], summary: 'Change the authenticated user password', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['currentPassword', 'newPassword', 'passwordConfirmation'], properties: { currentPassword: { type: 'string', format: 'password' }, newPassword: { type: 'string', format: 'password' }, passwordConfirmation: { type: 'string', format: 'password' } } } } } }, responses: { '204': { description: 'Password changed and active refresh tokens revoked.' } } } },
      '/auth/forgot-password': { post: { tags: ['Authentication'], summary: 'Request password reset', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['email'], properties: { email: { type: 'string', format: 'email' } } } } } }, responses: { '202': { description: 'Request accepted without disclosing account existence.' } } } },
      '/auth/reset-password': { post: { tags: ['Authentication'], summary: 'Reset a password with a single-use reset token', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['resetToken', 'newPassword', 'passwordConfirmation'], properties: { resetToken: { type: 'string' }, newPassword: { type: 'string', format: 'password' }, passwordConfirmation: { type: 'string', format: 'password' } } } } } }, responses: { '204': { description: 'Password reset.' }, '400': { description: 'Invalid or expired reset token.' } } } },
      '/users': { get: { tags: ['Users'], security: [{ bearerAuth: [] }], responses: { '200': { description: 'Users.' } } }, post: { tags: ['Users'], security: [{ bearerAuth: [] }], responses: { '201': { description: 'User created.' } } } },
      '/users/{id}': { parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }], get: { tags: ['Users'], security: [{ bearerAuth: [] }], responses: { '200': { description: 'User.' } } }, patch: { tags: ['Users'], security: [{ bearerAuth: [] }], responses: { '200': { description: 'Updated.' } } }, delete: { tags: ['Users'], security: [{ bearerAuth: [] }], responses: { '204': { description: 'Deactivated.' } } } },
      '/categories': { get: { tags: ['Categories'], security: [{ bearerAuth: [] }], responses: { '200': { description: 'Categories.' } } }, post: { tags: ['Categories'], security: [{ bearerAuth: [] }], responses: { '201': { description: 'Created.' } } } },
      '/categories/{id}': { parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }], get: { tags: ['Categories'], security: [{ bearerAuth: [] }], responses: { '200': { description: 'Category.' } } }, patch: { tags: ['Categories'], security: [{ bearerAuth: [] }], responses: { '200': { description: 'Updated.' } } }, delete: { tags: ['Categories'], security: [{ bearerAuth: [] }], responses: { '204': { description: 'Deleted.' } } } },
      '/products': { get: { tags: ['Products'], security: [{ bearerAuth: [] }], responses: { '200': { description: 'Products.' } } }, post: { tags: ['Products'], security: [{ bearerAuth: [] }], responses: { '201': { description: 'Created.' } } } },
      '/products/{id}': { parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }], get: { tags: ['Products'], security: [{ bearerAuth: [] }], responses: { '200': { description: 'Product.' } } }, patch: { tags: ['Products'], security: [{ bearerAuth: [] }], responses: { '200': { description: 'Updated.' } } }, delete: { tags: ['Products'], security: [{ bearerAuth: [] }], responses: { '204': { description: 'Deleted.' } } } },
      '/customers': { get: { tags: ['Customers'], security: [{ bearerAuth: [] }], responses: { '200': { description: 'Customers.' } } }, post: { tags: ['Customers'], security: [{ bearerAuth: [] }], responses: { '201': { description: 'Created.' } } } },
      '/customers/{id}': { parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }], get: { tags: ['Customers'], security: [{ bearerAuth: [] }], responses: { '200': { description: 'Customer.' } } }, patch: { tags: ['Customers'], security: [{ bearerAuth: [] }], responses: { '200': { description: 'Updated.' } } }, delete: { tags: ['Customers'], security: [{ bearerAuth: [] }], responses: { '204': { description: 'Deleted.' } } } },
      '/transactions': { get: { tags: ['Transactions'], security: [{ bearerAuth: [] }], responses: { '200': { description: 'Transactions.' } } }, post: { tags: ['Transactions'], security: [{ bearerAuth: [] }], responses: { '201': { description: 'Created.' } } } },
      '/transactions/{id}': { parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }], get: { tags: ['Transactions'], security: [{ bearerAuth: [] }], responses: { '200': { description: 'Transaction.' } } }, patch: { tags: ['Transactions'], security: [{ bearerAuth: [] }], responses: { '200': { description: 'Updated.' } } }, delete: { tags: ['Transactions'], security: [{ bearerAuth: [] }], responses: { '204': { description: 'Soft-deleted.' } } } },
      '/payments': { get: { tags: ['Payments'], security: [{ bearerAuth: [] }], responses: { '200': { description: 'Payments.' } } }, post: { tags: ['Payments'], security: [{ bearerAuth: [] }], responses: { '201': { description: 'Created.' } } } },
      '/payments/{id}': { parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }], get: { tags: ['Payments'], security: [{ bearerAuth: [] }], responses: { '200': { description: 'Payment.' } } }, patch: { tags: ['Payments'], security: [{ bearerAuth: [] }], responses: { '200': { description: 'Updated.' } } }, delete: { tags: ['Payments'], security: [{ bearerAuth: [] }], responses: { '204': { description: 'Deleted.' } } } }
    }
  },
  apis: []
});
